server:
  port: 8085

spring:

  spring:
    application:
      name: order-service



  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8900/eureka/



